-- Time Clash Chronicles Database Schema

SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS time_clash_chronicles;
CREATE SCHEMA time_clash_chronicles;
USE time_clash_chronicles;

CREATE TABLE card (
    card_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    attack INT UNSIGNED NOT NULL,
    health INT UNSIGNED NOT NULL,
    basic_attack VARCHAR(50) NOT NULL,
    cost INT UNSIGNED NOT NULL,
    nation VARCHAR(50) NOT NULL,
    leader_id SMALLINT UNSIGNED NOT NULL,
    ability_id SMALLINT UNSIGNED,
    deck_id SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (card_id),
    CONSTRAINT fk_card_leader FOREIGN KEY (leader_id) REFERENCES leader (leader_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_card_ability FOREIGN KEY (ability_id) REFERENCES ability (ability_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_card_deck FOREIGN KEY (deck_id) REFERENCES deck (deck_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player (
	player_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    wins INT UNSIGNED NOT NULL DEFAULT 0,
    loses INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (player_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE deck (
	deck_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    nation VARCHAR(50) NOT NULL,
    PRIMARY KEY (deck_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE leader (
    leader_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    ability_name VARCHAR(50) NOT NULL,
    leader_ability_id SMALLINT UNSIGNED NOT NULL,
    deck_id SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (leader_id),
    CONSTRAINT fk_leader_leader_ability FOREIGN KEY (leader_ability_id) REFERENCES leader_ability (leader_ability_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_leader_deck FOREIGN KEY (deck_id) REFERENCES deck (deck_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE player_deck (
  player_deck_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player_id SMALLINT UNSIGNED NOT NULL,
  deck_id SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (player_deck_id),
  CONSTRAINT fk_player_deck_player FOREIGN KEY (player_id) REFERENCES player (player_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_player_deck_deck FOREIGN KEY (deck_id) REFERENCES deck (deck_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE arena (
	arena_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
    nation VARCHAR(50) NOT NULL,

    PRIMARY KEY (arena_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE game (
  game_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  duration INT UNSIGNED NOT NULL,
  player1_id SMALLINT UNSIGNED NOT NULL,
  player2_id SMALLINT UNSIGNED NOT NULL,
  winner_id SMALLINT UNSIGNED NOT NULL,
  arena_id SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (game_id),
  CONSTRAINT fk_game_player1 FOREIGN KEY (player1_id) REFERENCES player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_game_player2 FOREIGN KEY (player2_id) REFERENCES player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_game_winner FOREIGN KEY (winner_id) REFERENCES player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_game_arena FOREIGN KEY (arena_id) REFERENCES arena (arena_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ability (
    ability_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    cost INT UNSIGNED NOT NULL,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY (ability_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE leader_ability (
    leader_ability_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    cost INT UNSIGNED NOT NULL,
    cooldown INT UNSIGNED NOT NULL,
    PRIMARY KEY (leader_ability_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;